server:
  port: 7000

spring:
  datasource:
    username: ${QUIZ_DB_USERNAME}
    url: ${QUIZ_DB_URL}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
