spring:
  profiles:
    active: defalt
---
spring:
  profiles: defalt
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${QUIZ_DB_USERNAME}
    url: ${QUIZ_DB_URL}
    type: org.apache.tomcat.jdbc.pool.DataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    changeLog: "classpath:db/changelog/changelog.xml"
    enabled: false
server:
  port: 8080
---
spring:
  profiles: test
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    changeLog: "classpath:db/changelog/changelog.xml"
    url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS postgres



