spring:
  profiles:
    active: defalt
---
spring:
  profiles: defalt
  datasource:
    driverClassName: org.postgresql.Driver
    username: plotva
    url: jdbc:postgresql://localhost:5432/postgres
    type: org.apache.tomcat.jdbc.pool.DataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    changeLog: "classpath:db/changelog/changelog.xml"
    enabled: false
server:
  port: 8080


