spring:
  profiles: dev
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${QUIZ_DB_USERNAME}
    password: ${QUIZ_DB_PASSWORD}
    url: ${QUIZ_DB_URL}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    changeLog: "classpath:db/changelog/changelog.xml"
server:
  port: 8080


